### ISSUE TITLE
 tdm read inbox error message

### ISSUE THREAD

**Issue by dcromster** [deleteman/tdm#5]
$ tdm read inbox
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Fri Jul 21 19:44:24 +0000 2017, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:320:94)
    at configFromString (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:2178:11)
    at configFromInput (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:2547:9)
    at prepareConfig (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:2530:9)
    at createFromConfig (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:2497:40)
    at createLocalOrUTC (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:2584:12)
    at createLocal (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:2588:12)
    at hooks (/usr/local/lib/node_modules/t-dm/node_modules/moment/moment.js:16:25)
    at /usr/local/lib/node_modules/t-dm/lib/commands/readCommand.js:30:23
    at Array.forEach (native)
--- 
But after that show me messages

**Comment by deleteman** [comment]
thanks for the bug report, commit  98b7f79  should take care of that.
